version: '2'

services:
  sonarqube:
    depends_on:
      - postgres
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      # - "9092:9092"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
       soft: 262144
       hard: 262144


  postgres:
    image: postgres
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data


  # scanner-app:
  #   networks:
  #     - sonarnet
  #   # depends_on:
  #   #   - sonarqube
  #   image: sonarsource/sonar-scanner-cli
  #   volumes:
  #     - './practicaSonar:/usr/src'
  #   environment:
  #    - SONAR_HOST_URL=https://jupegarnica-sonarqube-playground-qg6qj96h954v-9000.githubpreview.dev
  #    - SONAR_LOGIN=408af1d7fcb2ff363a941f46eb5239c7a661d583

  jenkins:
    depends_on:
      - sonarqube
    networks:
      - sonarnet
    image: jenkins/jenkins
    # environment:
    #   JENKINS_OPTS: "-d"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  maildev:
    networks:
      - sonarnet
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"
networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  jenkins_home:
