version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
      - ./sonarqube-data/sonarqube-conf:/opt/sonarqube/conf
      - ./sonarqube-data/sonarqube-data:/opt/sonarqube/data
      - ./sonarqube-data/sonarqube-logs:/opt/sonarqube/logs
      - ./sonarqube-data/sonarqube-extensions:/opt/sonarqube/extensions
