version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=bitnami1234
  sonarqube:
    image: bitnami/sonarqube:latest
    networks:
      - app-tier
    ports:
      - '9999:9000'
    environment:
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=bitnami1234
      - POSTGRESQL_CLIENT_DATABASE_HOST=postgresql
      - POSTGRESQL_CLIENT_DATABASE_PORT_NUMBER=5432
      - POSTGRESQL_CLIENT_DATABASE_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_DATABASE_ROOT_PASSWORD=bitnami1234
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local